config/routes.rb
Rails.application.routes.draw do
  root "photos#index"
  
  devise_for :passengers
  devise_for :drivers
  # Routes for the Photo resource:

  # CREATE
  get("/photos/new", { :controller => "photos", :action => "new_form" })
  post("/create_photo", { :controller => "photos", :action => "create_row" })

  # READ
  get("/photos", { :controller => "photos", :action => "index" })
  get("/photos/:id_to_display", { :controller => "photos", :action => "show" })

  # UPDATE
  get("/photos/:prefill_with_id/edit", { :controller => "photos", :action => "edit_form" })
  post("/update_photo/:id_to_modify", { :controller => "photos", :action => "update_row" })

  # DELETE
  get("/delete_photo/:id_to_remove", { :controller => "photos", :action => "destroy_row" })

  #------------------------------

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :caption, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, :keys => [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, :keys => [:first_name, :last_name])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all

    render("photo_templates/index.html.erb")
  end

  def show
    @photo = Photo.find(params[:id_to_display])

    render("photo_templates/show.html.erb")
  end

  def new_form
    @photo = Photo.new
    render("photo_templates/new_form.html.erb")
  end

  def create_row
    @photo = Photo.new

    @photo.image = params[:image]
    @photo.caption = params[:caption]

    save_status = @photo.save

    if save_status == true
      redirect_to("/photos", :notice => "Photo created successfully.")
    else
      render("photo_templates/new_form.html.erb")
    end
  end

  def edit_form
    @photo = Photo.find(params[:prefill_with_id])

    render("photo_templates/edit_form.html.erb")
  end

  def update_row
    @photo = Photo.find(params[:id_to_modify])

    @photo.image = params[:image]
    @photo.caption = params[:caption]

    save_status = @photo.save

    if save_status == true
      redirect_to("/photos/#{@photo.id}", :notice => "Photo updated successfully.")
    else
      render("photo_templates/edit_form.html.erb")
    end
  end

  def destroy_row
    @photo = Photo.find(params[:id_to_remove])

    @photo.destroy

    redirect_to("/photos", :notice => "Photo deleted successfully.")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    TestDraftGen3
  </title>

  <%= render "shared/bootstrapcdn_assets" %>

  <%= csrf_meta_tags %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta charset="utf-8">
  <style>
    body { padding-bottom: 70px }
  </style>
</head>

<body>
  <%= render "shared/navbar" %>

  <div class="container">
    <%= render "shared/flashes" %>

    <%= yield %>
  </div>

</body>
</html>

app/views/passengers/shared/_links.html.erb
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "btn btn-block btn-outline-secondary"  %>
  <% end -%>
<% end -%>

<%- if controller_name != "sessions" %>
  <%= link_to "Sign in", new_session_path(resource_name), class: "btn btn-block btn-outline-secondary" %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != "registrations" %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-block btn-outline-secondary"  %>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != "passwords" && controller_name != "registrations" %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "btn btn-block btn-sm btn-link"  %>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != "confirmations" %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "btn btn-block btn-sm btn-link"  %>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks" %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "btn btn-block btn-sm btn-link"  %>
<% end -%>

app/views/photo_templates/_create_form.html.erb
<form action="/create_photo" method="post">
  <!-- Label and input for image -->
  <div class="form-group">
    <label for="image">
      Image
    </label>

    <input type="text" id="image" name="image" class="form-control" value="<%= @photo.image %>">
  </div>

  <!-- Label and input for caption -->
  <div class="form-group">
    <label for="caption">
      Caption
    </label>

    <textarea id="caption" name="caption" class="form-control" rows="3"><%= @photo.caption %></textarea>
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Create photo
  </button>
</form>

app/views/photo_templates/_edit_form_validation_messages.html.erb
<% if @photo.errors.any? %>
  <% @photo.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/photo_templates/_new_form_validation_messages.html.erb
<% if @photo.errors.any? %>
  <% @photo.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/photo_templates/_photo_details.html.erb
<div class="card">
  <%= render "photo_templates/photo_details_card_header" %>

  <%= render "photo_templates/photo_details_card_body" %>

  <%= render "photo_templates/photo_details_card_footer" %>
</div>

app/views/photo_templates/_photo_details_card_body.html.erb
<div class="card-body">
  <dl>
    <dt>
      Image
    </dt>
    <dd>
      <%= @photo.image %>
    </dd>

    <dt>
      Caption
    </dt>
    <dd>
      <%= @photo.caption %>
    </dd>

    <dt>
      Created at
    </dt>
    <dd>
      <%= time_ago_in_words(@photo.created_at) %> ago
    </dd>

    <dt>
      Updated at
    </dt>
    <dd>
      <%= time_ago_in_words(@photo.updated_at) %> ago
    </dd>
  </dl>
</div>

app/views/photo_templates/_photo_details_card_footer.html.erb
<div class="card-footer">
  <div class="row">
    <div class="col">
      <a href="/photos/<%= @photo.id %>/edit" class="btn btn-block btn-outline-secondary">
        Edit photo
      </a>
    </div>

    <div class="col">
      <a href="/delete_photo/<%= @photo.id %>" class="btn btn-block btn-outline-secondary">
        Delete photo
      </a>
    </div>
  </div>
</div>

app/views/photo_templates/_photo_details_card_header.html.erb
<h1 class="card-header h4 d-flex align-items-center">
  <a href="/photos" class="btn btn-sm btn-outline-secondary mr-3">
    <i class="fas fa-chevron-left fa-fw"></i>
  </a>

  Photo #<%= @photo.id %> details
</h1>

app/views/photo_templates/_update_form.html.erb
<form action="/update_photo/<%= @photo.id %>" method="post">
  <!-- Label and input for image -->
  <div class="form-group">
    <label for="image">
      Image
    </label>

    <input type="text" id="image" name="image" class="form-control" value="<%= @photo.image %>">
  </div>

  <!-- Label and input for caption -->
  <div class="form-group">
    <label for="caption">
      Caption
    </label>

    <textarea id="caption" name="caption" class="form-control" rows="3"><%= @photo.caption %></textarea>
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Update photo
  </button>
</form>

app/views/photo_templates/edit_form.html.erb
<div class="row mb-3">
  <div class="col-md-8 offset-md-2">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center">
        <a href="/photos/<%= @photo.id %>" class="btn btn-sm btn-outline-secondary mr-3">
          <i class="fas fa-chevron-left fa-fw"></i>
        </a>

        Edit photo #<%= @photo.id %>
      </h1>

      <div class="card-body">
        <%= render "photo_templates/edit_form_validation_messages" %>

        <%= render "photo_templates/update_form" %>
      </div>
    </div>
  </div>
</div>

app/views/photo_templates/index.html.erb
<div class="row mb-3">
  <div class="col-md-8 offset-md-2">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        All photos

        <a href="/photos/new" class="btn btn-sm btn-outline-secondary">
          <i class="fas fa-plus fa-fw"></i>
        </a>
      </h1>

      <div class="list-group list-group-flush">
        <% @photos.each do |photo| %>
          <a href="/photos/<%= photo.id %>" class="list-group-item list-group-item-action d-flex align-items-center justify-content-between">
            Photo #<%= photo.id %>

            <span class="btn btn-sm btn-outline-secondary">
              <i class="fas fa-chevron-right fa-fw"></i>
            </span>
          </a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/photo_templates/new_form.html.erb
<div class="row mb-3">
  <div class="col-md-8 offset-md-2">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center">
        <a href="/photos" class="btn btn-sm btn-outline-secondary mr-3">
          <i class="fas fa-chevron-left fa-fw"></i>
        </a>

        Add a new photo
      </h1>

      <div class="card-body">
        <%= render "photo_templates/new_form_validation_messages" %>

        <%= render "photo_templates/create_form" %>
      </div>
    </div>
  </div>
</div>

app/views/photo_templates/show.html.erb
<div class="row mb-3">
  <div class="col-md-8 offset-md-2">
    <%= render "photo_templates/photo_details" %>
  </div>
</div>

app/views/shared/_bootstrapcdn_assets.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet"href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" >

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

app/views/shared/_flashes.html.erb
<div class="row">
  <div class="col-md-12">
    <% if notice.present? %>
      <div class="alert alert-success alert-dismissable">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert">
          <span>&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-warning alert-dismissable">
        <%= alert %>

        <button type="button" class="close" data-dismiss="alert">
          <span>&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <div class="container">
    <a class="navbar-brand" href="/">
      TestDraftGen3
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsible-nav-links">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsible-nav-links">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown">
            Resources
          </a>
          
          <div class="dropdown-menu">
            <a href="/photos" class="dropdown-item">
              Photos
            </a>
          </div>
        </li>
      </ul>

      <ul class="navbar-nav">
        <% if current_passenger.blank? %>
          <li class="nav-item">
            <a href="/passengers/sign_in" class="nav-link">
              Passenger sign in
            </a>
          </li>

          <li class="nav-item">
            <a href="/passengers/sign_up" class="nav-link">
              Passenger sign up
            </a>
          </li>
        <% else %>
          <li class="nav-item">
            <a href="/passengers/edit" class="nav-link">
              Passenger edit profile
            </a>
          </li>

          <li class="nav-item">
            <a href="/passengers/sign_out" data-method="delete" class="nav-link">
              Passenger sign out
            </a>
          </li>
        <% end %>
      </ul>

      <ul class="navbar-nav">
        <% if current_driver.blank? %>
          <li class="nav-item">
            <a href="/drivers/sign_in" class="nav-link">
              Driver sign in
            </a>
          </li>

          <li class="nav-item">
            <a href="/drivers/sign_up" class="nav-link">
              Driver sign up
            </a>
          </li>
        <% else %>
          <li class="nav-item">
            <a href="/drivers/edit" class="nav-link">
              Driver edit profile
            </a>
          </li>

          <li class="nav-item">
            <a href="/drivers/sign_out" data-method="delete" class="nav-link">
              Driver sign out
            </a>
          </li>
        <% end %>
      </ul>
    </div> <!-- .navbar-collapse -->
  </div> <!-- .container -->
</nav>